### ISSUE TITLE
 assert self.opt.model in ['srn', 'srn-hr']

### ISSUE THREAD

**Issue by chwangteng** [shepnerd/outpainting_srn#3]
Traceback (most recent call last):
  File "test.py", line 39, in <module>
    config = TestOptions().parse()
  File "/home/wt/outpainting_srn/options/test_options.py", line 66, in parse
    assert self.opt.model in ['srn', 'srn-hr']
AssertionError

**Comment by chwangteng** [comment]
--model srn

**Comment by zhangbaijin** [comment]
hello,the problem also trap me ,how should i solve it ? what's your mean? --model srn ?

**Comment by chwangteng** [comment]
> hello,the problem also trap me ,how should i solve it ? what's your mean? --model srn ?

把`--model srn`添加到作者给的命令里。  
model是一个必要的参数，但是根据错误提示看options/test_options.py里面23行，`default='vcp'`不对。

**Comment by chwangteng** [comment]
> hello,the problem also trap me ,how should i solve it ? what's your mean? --model srn ?

我是测试时候用的，没有训练过。

**Comment by zhangbaijin** [comment]
好的 我看到了  谢谢老哥 我也在测试 。

**Comment by zhangbaijin** [comment]
感觉蛮奇怪的，Failed to find any matching files for ./checkpoints/celebahq-srn-subpixel，明明这个文件夹我放了下载的预训练权重，还说找不到

**Comment by chwangteng** [comment]
> 感觉蛮奇怪的，Failed to find any matching files for ./checkpoints/celebahq-srn-subpixel，明明这个文件夹我放了下载的预训练权重，还说找不到

我是三个都下了，测试是没有问题的。
