### ISSUE TITLE
 The paris-streetview pretrained model with the Private links

### ISSUE THREAD

**Issue by erqiangli** [shepnerd/outpainting_srn#8]
Hi Yi Wang ,Can you share the paris-streetview pretrained model with the Private links.My email is 11360350@qq.com,Thanks a lot,Thanks for your amazing work!

**Comment by shepnerd** [comment]
It seems your provided email address is invalid. Your required model file can be downloaded from [here](https://drive.google.com/drive/folders/1ozhAvkW12bjuH9E8SkAbkjXAKg1JIwt4?usp=sharing).

**Comment by erqiangli** [comment]
It's my fault. Thank you for your patience




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yi Wang"<notifications@github.com&gt;; 
发送时间: 2020年1月6日(星期一) 晚上6:48
收件人: "shepnerd/outpainting_srn"<outpainting_srn@noreply.github.com&gt;; 
抄送: "李二强"<1136035076@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shepnerd/outpainting_srn]  The paris-streetview pretrained model with the Private links (#8)




It seems your provided email address is invalid. Your required model file can be downloaded from here.
